"""admin dashboard models

Revision ID: 9f31913ebf7e
Revises: 9e223f9df818
Create Date: 2026-07-08 19:00:09.752048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f31913ebf7e'
down_revision: Union[str, Sequence[str], None] = '9e223f9df818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynamic_parser_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('target_url_template', sa.String(), nullable=False),
    sa.Column('selectors', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dynamic_parser_rules_id'), 'dynamic_parser_rules', ['id'], unique=False)
    op.create_index(op.f('ix_dynamic_parser_rules_provider'), 'dynamic_parser_rules', ['provider'], unique=True)
    op.create_table('feature_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_id'), 'feature_flags', ['id'], unique=False)
    op.create_index(op.f('ix_feature_flags_key'), 'feature_flags', ['key'], unique=True)
    op.create_table('fraud_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('txn_id', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('flag_reason', sa.String(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['verification_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_queue_id'), 'fraud_queue', ['id'], unique=False)
    op.create_index(op.f('ix_fraud_queue_txn_id'), 'fraud_queue', ['txn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fraud_queue_txn_id'), table_name='fraud_queue')
    op.drop_index(op.f('ix_fraud_queue_id'), table_name='fraud_queue')
    op.drop_table('fraud_queue')
    op.drop_index(op.f('ix_feature_flags_key'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_id'), table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_dynamic_parser_rules_provider'), table_name='dynamic_parser_rules')
    op.drop_index(op.f('ix_dynamic_parser_rules_id'), table_name='dynamic_parser_rules')
    op.drop_table('dynamic_parser_rules')
    # ### end Alembic commands ###
