"""Initial tables

Revision ID: b12f37aea71b
Revises: 
Create Date: 2026-07-06 15:12:32.496008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b12f37aea71b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('verification_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expected_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'FAILED', 'EXPIRED', name='sessionstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_sessions_id'), 'verification_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_verification_sessions_token'), 'verification_sessions', ['token'], unique=True)
    op.create_table('transaction_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txn_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('payer_name', sa.String(), nullable=True),
    sa.Column('credited_party_account', sa.String(), nullable=True),
    sa.Column('settled_amount', sa.Float(), nullable=False),
    sa.Column('transaction_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['verification_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_receipts_id'), 'transaction_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_receipts_txn_id'), 'transaction_receipts', ['txn_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_receipts_txn_id'), table_name='transaction_receipts')
    op.drop_index(op.f('ix_transaction_receipts_id'), table_name='transaction_receipts')
    op.drop_table('transaction_receipts')
    op.drop_index(op.f('ix_verification_sessions_token'), table_name='verification_sessions')
    op.drop_index(op.f('ix_verification_sessions_id'), table_name='verification_sessions')
    op.drop_table('verification_sessions')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
