"""added new merchantand settings model modified verification model

Revision ID: d829cb5d2c39
Revises: b12f37aea71b
Create Date: 2026-07-07 22:00:33.291416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd829cb5d2c39'
down_revision: Union[str, Sequence[str], None] = 'b12f37aea71b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_phone', sa.String(), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_api_key_hash'), 'merchants', ['api_key_hash'], unique=True)
    op.create_index(op.f('ix_merchants_id'), 'merchants', ['id'], unique=False)
    op.create_index(op.f('ix_merchants_name'), 'merchants', ['name'], unique=False)
    op.create_index(op.f('ix_merchants_telegram_user_id'), 'merchants', ['telegram_user_id'], unique=True)
    op.create_table('platform_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monthly_fee', sa.Float(), nullable=False),
    sa.Column('receiver_phone', sa.String(), nullable=False),
    sa.Column('receiver_name', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_settings_id'), 'platform_settings', ['id'], unique=False)
    op.add_column('verification_sessions', sa.Column('merchant_id', sa.Integer(), nullable=False))
    op.add_column('verification_sessions', sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'verification_sessions', 'merchants', ['merchant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_sessions', type_='foreignkey')
    op.drop_column('verification_sessions', 'metadata_payload')
    op.drop_column('verification_sessions', 'merchant_id')
    op.drop_index(op.f('ix_platform_settings_id'), table_name='platform_settings')
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_merchants_telegram_user_id'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_name'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_id'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_api_key_hash'), table_name='merchants')
    op.drop_table('merchants')
    # ### end Alembic commands ###
